### PR TITLE
Avoid throwing an exception to break set.forEach

### PR DESCRIPTION
**Pull request by Yomguithereal**
Hello @robbie-c. Just a tiny change to avoid throwing an error to break the set.forEach method in the `isEqual` util.

### CODE REVIEW

**Comment by robbie-c** [comment]
I worry that this will break old IE support. I don't know how much I care but I think if we do break it, it should be to provide more functionality, rather than to make the code neater.

I'd like to do https://github.com/robbie-c/js-set-functions/issues/11 so we can actually test this before merging this.

**Comment by robbie-c** [comment]
Now that I have browser tests set up, I can revisit this. If it doesn't break IE9 (or anything more recent ofc) then that's fine with me.

**Comment by Yomguithereal** [comment]
Hello @robbie-c. I have implemented functions similar to your library's in one of mine recently because I needed some more. You can find them [here](https://github.com/Yomguithereal/mnemonist/blob/master/set.js). Feel free to use whatever you need.

**Comment by robbie-c** [comment]
Nice repo! Would you be interested in a PR for setting up cross browser testing with Sauce Labs?

**Comment by Yomguithereal** [comment]
Sure, why not?

**Pull request closed without merging**
